### ISSUE TITLE
Connection wrapper support

### ISSUE THREAD

**Issue by JanMikes** [nettrine/orm#18]
Hi, we need to use Connection Wrapper (https://www.doctrine-project.org/projects/doctrine-dbal/en/2.7/reference/configuration.html#wrapper-class).

Is that possible with nettrine and what would be the best way? Previously in kdyby/doctrine there was a config option for that.

**Comment by f3l1x** [comment]
It's not possible at this moment, but looks usefult. Could you please send a PR? I think put it into configuration would be enought?

**Comment by JanMikes** [comment]
Sure, though i think i have chosen wrong repo as imho it is dbal related instead of orm.
