### ISSUE TITLE
Long time no release

### ISSUE THREAD

**Issue by jiripudil** [nettrine/orm#21]
For those of us who prefer the sense of stability coming from tagged releases as opposed to dev-master, would you care to tag a new one? I've stumbled upon a bug in 0.1 that breaks the default (!) configuration (wrong `is_subclass_of` in `OrmCacheExtension`) and that is hopefully fixed in master by 62526fb. Thank you :)

**Comment by f3l1x** [comment]
Sure. I will release it today. :-)

**Comment by jiripudil** [comment]
Thanks!

**Comment by f3l1x** [comment]
Done ;-)
