### ISSUE TITLE
kdyby/doctrine compatibility/features

### ISSUE THREAD

**Issue by MartkCz** [nettrine/orm#24]
Hi,
I love and very often use methods from kdyby/doctrine:
Repository -> findBy, findOneBy, countBy, findPairs
QueryBuilder -> whereCriteria

I know, that you want keep light version of doctrine, so we can add this methods as trait and add replacement of built-in QueryBuilder as option to DI. I can send PR, when you fix #8

**Comment by f3l1x** [comment]
If you keep it lightweight I agree. :+1:

**Comment by f3l1x** [comment]
Any updates @MartkCz?

**Comment by MartkCz** [comment]
Need https://github.com/nettrine/orm/issues/8 fix for custom query builder registration.

**Comment by f3l1x** [comment]
@MartkCz #8 + #22 done ;-)

**Comment by mabar** [comment]
Is that issue still relevant?

**Comment by f3l1x** [comment]
Closing due neactivity. Feel free to open it.
