### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by xpackal5** [nettrine/orm#28]
Problem 1
    - symfony/console v4.1.1 requires php ^7.1.3 -> your PHP version (7.1.17-0ubuntu0.17.10.1) overridden by "config.platform.php" version (7.1) does not satisfy that requirement.
    - symfony/console v4.1.0 requires php ^7.1.3 -> your PHP version (7.1.17-0ubuntu0.17.10.1) overridden by "config.platform.php" version (7.1) does not satisfy that requirement.
    - symfony/console v4.0.9 requires php ^7.1.3 -> your PHP version (7.1.17-0ubuntu0.17.10.1) overridden by "config.platform.php" version (7.1) does not satisfy that requirement.
    - symfony/console v4.0.8 requires php ^7.1.3 -> your PHP version (7.1.17-0ubuntu0.17.10.1) overridden by "config.platform.php" version (7.1) does not satisfy that requirement.
    - symfony/console v4.0.12 requires php ^7.1.3 -> your PHP version (7.1.17-0ubuntu0.17.10.1) overridden by "config.platform.php" version (7.1) does not satisfy that requirement.
    - symfony/console v4.0.11 requires php ^7.1.3 -> your PHP version (7.1.17-0ubuntu0.17.10.1) overridden by "config.platform.php" version (7.1) does not satisfy that requirement.
    - symfony/console v4.0.10 requires php ^7.1.3 -> your PHP version (7.1.17-0ubuntu0.17.10.1) overridden by "config.platform.php" version (7.1) does not satisfy that requirement.
    - nettrine/orm v0.2.1 requires symfony/console ^4.0.8 -> satisfiable by symfony/console[v4.0.10, v4.0.11, v4.0.12, v4.0.8, v4.0.9, v4.1.0, v4.1.1].
    - Installation request for nettrine/orm ^0.2.1 -> satisfiable by nettrine/orm[v0.2.1]

**Comment by xpackal5** [comment]
works if set project dependency php 7.1.3

**Comment by f3l1x** [comment]
Hi, thanks for an issue. I dont see any problem on nettrine’s side. What behaviour do you expect?

**Comment by mabar** [comment]
@f3l1x We should not probably require so specific versions of symfony/console if package work with lower versions (^4.0.0 at least)

@xpackal5 `config.platform.php` do almost the same as `composer.lock`. I recommend you prefer lock file.
`config.platform.php` literally deny you install newer dependencies then for php version defined in platform config (7.1.0 in your case)
