### ISSUE TITLE
Class 'Nettrine\Dbal\DI\DbalExtension' not found

### ISSUE THREAD

**Issue by haelexuis** [nettrine/orm#29]
Hello, it was long time ago I was using nette, so I installed sandbox and nettrine according to https://github.com/nettrine/orm/blob/master/.docs/README.md#minimal-configuration, and it still throws error that class was not found (Class 'Nettrine\Dbal\DI\DbalExtension' not found). Could you please help me out?

My config.neon, composer.json and exception are in the zip archive.
[error.zip](https://github.com/nettrine/orm/files/2190653/error.zip)

**Comment by haelexuis** [comment]
I have included vendor autoloader and robotloader in my bootstrap PHP, it was clean nette/sandbox installed via composer.

**Comment by f3l1x** [comment]
Could you please send config here?

**Comment by haelexuis** [comment]
Yes, minimum stability is dev, but it didn't work with stable too.
{
	"name": "nette/sandbox",
	"description": "The sandbox is a pre-packaged Nette Framework project, basic configured structure for your application.",
	"homepage": "https://nette.org",
	"type": "project",
	"license": ["BSD-3-Clause", "GPL-2.0", "GPL-3.0"],
	"authors": [
		{
			"name": "David Grudl",
			"homepage": "https://davidgrudl.com"
		},
		{
			"name": "Nette Community",
			"homepage": "https://nette.org/contributors"
		}
	],
	"require": {
		"php": ">=7.1.0",
		"nette/application": "^2.4.4",
		"nette/bootstrap": "^2.4.3",
		"nette/caching": "^2.5",
		"nette/database": "^2.4",
		"nette/di": "^2.4",
		"nette/finder": "^2.4",
		"nette/forms": "^2.4",
		"nette/http": "^2.4",
		"nette/mail": "^2.4",
		"nette/robot-loader": "^2.4 || ^3.0",
		"nette/safe-stream": "^2.3",
		"nette/security": "^2.4",
		"nette/utils": "^2.4",
		"latte/latte": "^2.4",
		"tracy/tracy": "^2.4",
		"dg/adminer-custom": "^1.9",
		"nettrine/orm": "dev-master",
		"kdyby/console": "^2.7",
		"nettrine/dbal": "dev-master",
		"contributte/console": "^0.5.0"
	},
	"require-dev": {
		"nette/tester": "^2.0"
	},
	"minimum-stability": "dev",
	"config": {
		"platform": {
			"php": "7.1.17"
		}
	}
}

**Comment by haelexuis** [comment]
Okay, problem solved, please edit

```
extensions:
    dbal: Nettrine\Dbal\DI\DbalExtension
```
to
```
extensions:
    dbal: Nettrine\DBAL\DI\DbalExtension
```

in
https://github.com/nettrine/dbal/tree/master/.docs#installation

**Comment by f3l1x** [comment]
Thanks.
