### ISSUE TITLE
OrmExtension

### ISSUE THREAD

**Issue by aleswita** [nettrine/orm#3]
You are using current version of dev-master in our project?

On my project extension still throws this exception "AnnotationReader missing in DIC, please use Nettrine/Annotations or implement own MetadataProvider."

It's because, that [getByType](https://github.com/nettrine/orm/blob/master/src/DI/OrmExtension.php#L91) method returning still null, because anotation extension set anotation reader as autowired = false.
Look at the docs: https://api.nette.org/2.4/source-DI.ContainerBuilder.php.html#225

I think this is correct:
```
if (count($builder->findByType(AnnotationReader::class)) === 0) {
	throw new \Exception('AnnotationReader missing in DIC, please use Nettrine/Annotations or implement own MetadataProvider.');
}
```

**Comment by aleswita** [comment]
..or what you think about this:
```php
$reader = $builder->getByType(AnnotationReader::class);

if ($reader === null) {
	$readers = $builder->findByType(AnnotationReader::class);

	if (count($readers) === 0) {
		throw new \Exception('AnnotationReader missing in DIC, please use Nettrine/Annotations or implement own MetadataProvider.');

	} elseif (count($readers) > 1) {
		throw new \Exception('Multiple services of type "Doctrine\\Common\\Annotations\\AnnotationReader".');
	}

	$reader = end($readers);			
}

$annotationDriver = $builder->addDefinition($this->prefix('annotationDriver'))
	->setType(AnnotationDriver::class)
	->setArguments([$reader, $builder->expand('%appDir%')]);

$configuration->addSetup('setMetadataDriverImpl', [$annotationDriver]);

**Comment by f3l1x** [comment]
What about change autowired to `TRUE`? It would solve this problem. :-)

**Comment by aleswita** [comment]
👍 

I will send PR.
