### ISSUE TITLE
Missing "orm:clear-cache:metadata" command

### ISSUE THREAD

**Issue by khorsky** [nettrine/orm#31]
Is there any specific reason, why have you omitted [MetadataCommand](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Tools/Console/Command/ClearCache/MetadataCommand.php) in OrmConsoleExtension?

I'm using "orm:schema-tool:update" for generating diff, but I've to manually delete cache to have proper results.

Have I missed something in documentation? What is the preferred way to use "orm:schema-tool:update" correctly?

**Comment by f3l1x** [comment]
Hi, there's no reason as much I know. Could you prepare PR?
