### ISSUE TITLE
Minimal documentation

### ISSUE THREAD

**Issue by xpavp03** [nettrine/orm#4]
@enumag [recommended Nettrine](Kdyby/Doctrine#306) as a replacement for Kdyby/Doctrine however, I can't find any information on how to use it. Could you please provide at least some set-up instructions, or a link somewhere where this has been discussed?

Thanks

**Comment by enumag** [comment]
Nettrine is hopefully a future replacement but it's far from beign ready to use.

**Comment by f3l1x** [comment]
Hi @xpavp03, thanks for an issue. Set the minimal readme will be solved next week. I let you know.

**Comment by f3l1x** [comment]
@xpavp03 Could you take a look at now? I think it's good for the beginning.
