### ISSUE TITLE
compatibility with nette 3

### ISSUE THREAD

**Issue by matlad** [nettrine/orm#44]
I there way to run nettrine/orm with Nette 3?
When i try require with composer nettrine/orm a get conflict:
 Problem 1
    - Can only install one of: nette/di[v2.4.x-dev, 3.0.x-dev].
    - Can only install one of: nette/di[v3.0.0-alpha1, v2.4.x-dev].
    - Can only install one of: nette/di[v3.0.0-beta1, v2.4.x-dev].
    - Can only install one of: nette/di[v3.0.0-beta2, v2.4.x-dev].
    - nettrine/orm 0.3.x-dev requires nette/di ~2.4.14 -> satisfiable by nette/di[v2.4.x-dev].
    - Installation request for nettrine/orm ^0.3.0@dev -> satisfiable by nettrine/orm[0.3.x-dev].
    - Installation request for nette/di ^3.0 -> satisfiable by nette/di[3.0.x-dev, v3.0.0-alpha1, v3.0.0-beta1, v3.0.0-beta2].

**Comment by MartkCz** [comment]
I use
```json
"require": {
	"nette/di": "v3.0.x-dev as 2.4.x-dev",
	"nette/utils": "v3.0.x-dev as 2.5.x-dev",
```

**Comment by f3l1x** [comment]
Nette 3.0 is not released yet. Please use aliasing as @MartkCz mentioned.

**Comment by matlad** [comment]
Thanx, (Do you think it's safe? Or better formulated, do you know about any problems with compatibility?)

**Comment by mabar** [comment]
Composer acts like `use 3.0 version but tell packages which need it that it's a 2.4`. So it is safe only if these versions are compatible. But it's the only solution before we create branch for nette 3 and before nette 3 is released.

**Comment by mabar** [comment]
Btw, it should be `v3.0.x-dev as 2.4.15`. You usually want use it as latest possible version, not as oldest.

**Comment by janvorisek** [comment]
Anyone working on the issue? As Nette 3 has been officially released recently.

**Comment by mabar** [comment]
https://github.com/nettrine/orm/pull/48

**Comment by mabar** [comment]
Stable version tagged
