### ISSUE TITLE
ManagerRegistry::resetManager does not reset the inner EntityManager

### ISSUE THREAD

**Issue by redwormik** [nettrine/orm#58]
Hi,

when I want to reset the entity manager via ManagerRegistry::resetManager, only the decorator gets recreated, the inner EntityManager stays the same.

I guess the solution would be to remove the `orm.entityManager` service altogether and create it via DI Statement:

In OrmExtension::loadEntityManagerConfiguration()
```
		// Entity Manager
		$original = new Statement(DoctrineEntityManager::class . '::create', [
			$builder->getDefinitionByType(Connection::class), // Nettrine/DBAL
			$this->prefix('@configuration'),
		]);

		// Entity Manager Decorator
		$builder->addDefinition($this->prefix('entityManagerDecorator'))
			->setFactory($entityManagerDecoratorClass, [$original]);
```

In generated DI container:
```
	public function createServiceOrm__entityManagerDecorator(): Nettrine\ORM\EntityManagerDecorator
	{
		return new Nettrine\ORM\EntityManagerDecorator(Doctrine\ORM\EntityManager::create(
			$this->getService('dbal.connection'),
			$this->getService('orm.configuration'),
			$this->getService('dbal.eventManager')
		));
	}
```

If this approach is OK (or if you suggest another approach), I would gladly prepare a PR. (I know this conflicts with open PR #47, I can wait until it is merged.)

**Comment by f3l1x** [comment]
Looks good to me, you can prepare a PR + covered this issue with tests. Then we can test it.
