### ISSUE TITLE
XML mapper support?

### ISSUE THREAD

**Issue by JanMikes** [nettrine/orm#6]
Hi, planning a XML mapping support for this package?

**Comment by Lexinek** [comment]
Maybe 😄 i will do some research as implementation of https://github.com/nettrine/orm/blob/master/src/Mapping/AnnotationDriver.php seems very easy!

**Comment by benijo** [comment]
It would be good to have it as separate extension, something like OrmXmlExtension

**Comment by f3l1x** [comment]
Hi @JanMikes. Any progress here? Could you please elaborate on OrmXmlExtension? :-)

**Comment by JanMikes** [comment]
Hi, sorry no progress as we are migrating whole application from Nette to Symfony.
