### ISSUE TITLE
Custom DQL functions

### ISSUE THREAD

**Issue by MartinSzollos2016** [nettrine/orm#65]
Hi, 
is there a way to register custom DQL function like in Kdyby/Doctrine ?
https://github.com/kdyby/doctrine/blob/master/docs/en/configuring.md#user-content-orm

**Comment by mabar** [comment]
custom*Functions

https://github.com/nettrine/orm/blob/master/.docs/README.md#configuration

**Comment by MartinSzollos2016** [comment]
Thx. I overlooked it in the documentation.
