### ISSUE TITLE
Doctrine Filters - regitration in NEON config

### ISSUE THREAD

**Issue by patrickkusebauch** [nettrine/orm#71]
A follow up on this nette forum discussion: https://forum.nette.org/cs/31618-nettrine-extensions-neaplikuje-se-filtr

The post mentioned it is not yet implemented and I was unable to find it in master branch code.

If there is a demand, I would be willing to make a PR - I have too much free time on my hands anyways with the current situation.

**Comment by f3l1x** [comment]
🏃 go for that! :-)

**Comment by patrickkusebauch** [comment]
```neon
orm:
	configuration:
		filters:
			softdeleteable:
				class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
				enabled: true
```

The proposed syntax sound good to you @f3l1x ?

**Comment by f3l1x** [comment]
Sure. Do you even need to disable it? I mean, you don't have to register it at all. WDYT?

**Comment by patrickkusebauch** [comment]
I think the idea is the other way around. You might want to register it but not enable it straight away. And enable it on a case by case basis in the code. This syntax would be a shortcut to enable it straight away for all cases.

**Comment by f3l1x** [comment]
Oh, I see. Good point. Agree with syntax.
