### ISSUE TITLE
Incompatible with latest doctrine

### ISSUE THREAD

**Issue by akadlec** [nettrine/orm#78]
Laster version of doctrine orm (2.7.3) is not compatible due to namespaces changes `Doctrine\Common\Persistence` -> `Doctrine\Persistence` which is cause by dependency: `"doctrine/common": "^2.11 || ^3.0",`

To fix this probem, had to define doctrine orm 2.7.2 in my project.

So, just to inform you

**Comment by f3l1x** [comment]
Thanks @akadlec. I don't get it why this change affected 2.x version. :-) We need to be more strict about it.

**Comment by lukyrys** [comment]
Incompatibility is from class  'Doctrine\**Common**\Persistence\AbstractManagerRegistry'
In 2.x version they dropped from namespace "Common" .. now is AbstractManagerRegistry in namespace Doctrine\Persistence\AbstractManagerRegistry

**Comment by vody105** [comment]
@f3l1x This seems solved. You can close it.

**Comment by f3l1x** [comment]
Yep
