### ISSUE TITLE
Custom RepositoryFactory cannot be set

### ISSUE THREAD

**Issue by jahudka** [nettrine/orm#79]
Hi, the `Nettrine\ORM\DI\OrmExtension` class defines in the config schema that the `configuration.repositoryFactory` property must be a string, but when I use one, the generated service factory passes the string as a literal to the `$service->setRepositoryFactory()` call, but the method expects an _instance_ of the repository factory. If I set the repository factory to a Neon entity instead (basically just append `()` to the class name) schema validation fails, because I'm no longer passing a string where one is expected.

**Workaround:** set the repository factory manually in `services`:

```neon
services:
  # ...
  nettrine.orm.configuration:
    alteration: true
    setup:
      - setRepositoryFactory(My\Repository\Factory())
```

I'll look into writing a PR to fix this, but it won't be today..

**Comment by f3l1x** [comment]
Hey @jahudka. Thanks for report. 

I think we can allow string and service definition as well. :-)

**Comment by f3l1x** [comment]
Resolved in https://github.com/nettrine/orm/commit/2626b7cc05dfc03abfd9cd8b056df4557907eea7
