### ISSUE TITLE
Any ETA on stable version supporting PHP 8?

### ISSUE THREAD

**Issue by racinmat** [nettrine/orm#88]
Hi, `nettrine/orm` is not compatible with PHP 8, because:
it has dependency `doctrine/common: ^2.13.1`, 
which is compatible with `doctrine/orm` version 2.7.5, because it has dependencies
```
php: ^7.1
doctrine/common: ^2.11 || ^3.0
```
but `doctrine/orm` version 2.8.0, has dependencies
```
php: ^7.2|^8.0
doctrine/common: ^3.0
```

and because of this clash, composer enforces usage of `doctrine/orm` < 2.8.0, which is not compatible with PHP 8.
I hope having
`doctrine/common: ^2.13.1 || ^3.0`
instead of 
`doctrine/common: ^2.13.1`
would solve it.

**Comment by racinmat** [comment]
Ok, I see it has been resolved in https://github.com/nettrine/orm/commit/4ddb1018ad31d6bf8a5f6d7fc47457afbe191b11, but that's not released yet.

**Comment by f3l1x** [comment]
Solved https://github.com/nettrine/orm/releases/tag/v0.8.1, thanks.
