### ISSUE TITLE
Support of mapping using php 8 attributes

### ISSUE THREAD

**Issue by LukasVitek** [nettrine/orm#95]
I can't get mapping to work using php 8 attributes.
Please add support or create documentation for this functionality.
(https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/reference/attributes-reference.html)

**Comment by mesour** [comment]
@LukasVitek I modified the bottom of`OrmAnnotationsExtension::loadConfiguration` as follows:

You must change `AnnotationDriver` to `AttributeDriver`. It is only an experimental version, it could be written better.

```
foreach ($config->mapping as $path) {
	if (!is_dir($path)) {
		throw new InvalidStateException(sprintf('Given mapping path "%s" does not exist', $path));
	}
}

$builder->addDefinition($this->prefix('annotationDriver'))
	->setFactory(AttributeDriver::class, [array_values($config->mapping)])
	->setType(AttributeDriver::class)
	->addSetup('addExcludePaths', [$config->excludePaths])
	->addTag(self::DRIVER_TAG)
	->setAutowired(false);

$mappingDriverDef = $this->getMappingDriverDef();
foreach ($config->mapping as $namespace => $path) {
	$mappingDriverDef->addSetup('addDriver', [$this->prefix('@annotationDriver'), $namespace]);
}
```

**Comment by Rixafy** [comment]
@mesour annotationDriver can still be added with attributeDriver side by side, or not? Driver tag would need to be different probably, and @f3l1x do you have an idea how to add support for attributes without BC break? I'm not very experienced with nette schema syntax and if it allows to have 2 different syntaxes so it wouldn't break current syntax. 

Symfony has it like this https://github.com/doctrine/DoctrineBundle/blob/2.4.x/DependencyInjection/DoctrineExtension.php#L714 and current nettrine syntax for mapping is `App\Model: %appDir%/Model`, that would needed to change to something like
```neon
App\Model: 
    dir: %appDir%/Model
    type: attribute
```

**Comment by Rixafy** [comment]
Ah, now I see, there are separated classes for different types (annotations/yaml etc), so we only need OrmAttributesExtension class.

**Comment by mesour** [comment]
@Rixafy yes, we need only `OrmAttributesExtension` and maybe a few changes in the extension configuration structure (In my example, I kept the configuration because I only send one element to the `mapping` field.).

**Comment by Rixafy** [comment]
@mesour there are no changes needed because I didn't realized at first glance that for every mapping type there is a separate extension, you can try to install this branch https://github.com/Rixafy/orm/tree/attributes to composer if it works correctly

**Comment by f3l1x** [comment]
Seems good, https://github.com/nettrine/orm/pull/96

**Comment by f3l1x** [comment]
Solved via https://github.com/nettrine/orm/pull/96
